// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ActionSummary action summary
//
// swagger:model ActionSummary
type ActionSummary struct {

	// count
	Count int64 `json:"count,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// points
	Points float64 `json:"points,omitempty"`
}

// Validate validates this action summary
func (m *ActionSummary) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this action summary based on context it is used
func (m *ActionSummary) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ActionSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActionSummary) UnmarshalBinary(b []byte) error {
	var res ActionSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
