// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// BlockchainStatus blockchain status
//
// swagger:model BlockchainStatus
type BlockchainStatus int64

// for schema
var blockchainStatusEnum []interface{}

func init() {
	var res []BlockchainStatus
	if err := json.Unmarshal([]byte(`[0,1,2,3,4]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		blockchainStatusEnum = append(blockchainStatusEnum, v)
	}
}

func (m BlockchainStatus) validateBlockchainStatusEnum(path, location string, value BlockchainStatus) error {
	if err := validate.EnumCase(path, location, value, blockchainStatusEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this blockchain status
func (m BlockchainStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateBlockchainStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this blockchain status based on context it is used
func (m BlockchainStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
