// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CardPackType card pack type
//
// swagger:model CardPackType
type CardPackType struct {

	// card pack code
	CardPackCode string `json:"card_pack_code"`

	// id
	ID string `json:"id"`

	// name
	Name string `json:"name"`

	// pack limits
	PackLimits int64 `json:"pack_limits"`
}

// Validate validates this card pack type
func (m *CardPackType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this card pack type based on context it is used
func (m *CardPackType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CardPackType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CardPackType) UnmarshalBinary(b []byte) error {
	var res CardPackType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
