// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DivisionReward division reward
//
// swagger:model DivisionReward
type DivisionReward struct {

	// amount
	Amount int64 `json:"amount,omitempty"`

	// balls
	Balls int64 `json:"balls"`

	// event
	Event int64 `json:"event"`

	// game
	Game float64 `json:"game"`

	// kick off pack 1
	KickOffPack1 int64 `json:"kick_off_pack_1"`

	// kick off pack 2
	KickOffPack2 int64 `json:"kick_off_pack_2"`

	// kick off pack 3
	KickOffPack3 int64 `json:"kick_off_pack_3"`

	// lapt
	Lapt float64 `json:"lapt"`

	// max position
	MaxPosition int64 `json:"max_position,omitempty"`

	// min position
	MinPosition int64 `json:"min_position,omitempty"`

	// season pack 1
	SeasonPack1 int64 `json:"season_pack_1"`

	// season pack 2
	SeasonPack2 int64 `json:"season_pack_2"`

	// season pack 3
	SeasonPack3 int64 `json:"season_pack_3"`

	// shirts
	Shirts int64 `json:"shirts"`

	// signed balls
	SignedBalls int64 `json:"signed_balls"`

	// signed shirts
	SignedShirts int64 `json:"signed_shirts"`
}

// Validate validates this division reward
func (m *DivisionReward) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this division reward based on context it is used
func (m *DivisionReward) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DivisionReward) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DivisionReward) UnmarshalBinary(b []byte) error {
	var res DivisionReward
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
