// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GameJoinRequest game join request
//
// swagger:model GameJoinRequest
type GameJoinRequest struct {

	// match id
	// Required: true
	MatchID *string `json:"match_id"`

	// picks
	// Required: true
	Picks []string `json:"picks"`
}

// Validate validates this game join request
func (m *GameJoinRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMatchID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePicks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GameJoinRequest) validateMatchID(formats strfmt.Registry) error {

	if err := validate.Required("match_id", "body", m.MatchID); err != nil {
		return err
	}

	return nil
}

func (m *GameJoinRequest) validatePicks(formats strfmt.Registry) error {

	if err := validate.Required("picks", "body", m.Picks); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this game join request based on context it is used
func (m *GameJoinRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GameJoinRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GameJoinRequest) UnmarshalBinary(b []byte) error {
	var res GameJoinRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
