// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GlobalLeaderBoardEntry global leader board entry
//
// swagger:model GlobalLeaderBoardEntry
type GlobalLeaderBoardEntry struct {

	// The rank of the user
	Rank int64 `json:"rank,omitempty"`

	// total score
	TotalScore float64 `json:"total_score,omitempty"`

	// The user ID
	UserID string `json:"user_id,omitempty"`

	// The user name
	UserName string `json:"user_name,omitempty"`
}

// Validate validates this global leader board entry
func (m *GlobalLeaderBoardEntry) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this global leader board entry based on context it is used
func (m *GlobalLeaderBoardEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GlobalLeaderBoardEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GlobalLeaderBoardEntry) UnmarshalBinary(b []byte) error {
	var res GlobalLeaderBoardEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
