// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LatestMatchStat latest match stat
//
// swagger:model LatestMatchStat
type LatestMatchStat struct {

	// min played
	MinPlayed int64 `json:"min_played,omitempty"`

	// points
	Points int64 `json:"points,omitempty"`

	// team crest url
	TeamCrestURL string `json:"team_crest_url,omitempty"`

	// team name
	TeamName string `json:"team_name,omitempty"`
}

// Validate validates this latest match stat
func (m *LatestMatchStat) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this latest match stat based on context it is used
func (m *LatestMatchStat) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LatestMatchStat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LatestMatchStat) UnmarshalBinary(b []byte) error {
	var res LatestMatchStat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
