// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LeaderboardPosition leaderboard position
//
// swagger:model LeaderboardPosition
type LeaderboardPosition struct {

	// position
	Position *int64 `json:"position"`
}

// Validate validates this leaderboard position
func (m *LeaderboardPosition) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this leaderboard position based on context it is used
func (m *LeaderboardPosition) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LeaderboardPosition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LeaderboardPosition) UnmarshalBinary(b []byte) error {
	var res LeaderboardPosition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
