// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MatchRule match rule
//
// swagger:model MatchRule
type MatchRule struct {

	// max star player picks
	MaxStarPlayerPicks int64 `json:"max_star_player_picks,omitempty"`

	// num of picks
	NumOfPicks int64 `json:"num_of_picks,omitempty"`
}

// Validate validates this match rule
func (m *MatchRule) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this match rule based on context it is used
func (m *MatchRule) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MatchRule) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MatchRule) UnmarshalBinary(b []byte) error {
	var res MatchRule
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
