// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MatchHeadline match headline
//
// swagger:model MatchHeadline
type MatchHeadline struct {

	// description
	Description string `json:"description"`

	// image type
	ImageType string `json:"image_type"`

	// images
	Images []string `json:"images"`

	// title
	Title string `json:"title"`

	// type
	Type string `json:"type"`
}

// Validate validates this match headline
func (m *MatchHeadline) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this match headline based on context it is used
func (m *MatchHeadline) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MatchHeadline) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MatchHeadline) UnmarshalBinary(b []byte) error {
	var res MatchHeadline
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
