// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// MatchType status of game
//
// swagger:model MatchType
type MatchType int64

// for schema
var matchTypeEnum []interface{}

func init() {
	var res []MatchType
	if err := json.Unmarshal([]byte(`[0,1,2,3]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		matchTypeEnum = append(matchTypeEnum, v)
	}
}

func (m MatchType) validateMatchTypeEnum(path, location string, value MatchType) error {
	if err := validate.EnumCase(path, location, value, matchTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this match type
func (m MatchType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateMatchTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this match type based on context it is used
func (m MatchType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
