// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelShortUser model short user
//
// swagger:model model.ShortUser
type ModelShortUser struct {

	// avatar url
	AvatarURL string `json:"avatar_url,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// influencer
	Influencer bool `json:"influencer,omitempty"`

	// moderator
	Moderator bool `json:"moderator,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// premium
	Premium bool `json:"premium,omitempty"`

	// subscription tier
	SubscriptionTier struct {
		ModelSubscriptionTier
	} `json:"subscription_tier,omitempty"`

	// verified
	Verified bool `json:"verified,omitempty"`
}

// Validate validates this model short user
func (m *ModelShortUser) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubscriptionTier(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelShortUser) validateSubscriptionTier(formats strfmt.Registry) error {
	if swag.IsZero(m.SubscriptionTier) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this model short user based on the context it is used
func (m *ModelShortUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSubscriptionTier(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelShortUser) contextValidateSubscriptionTier(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *ModelShortUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelShortUser) UnmarshalBinary(b []byte) error {
	var res ModelShortUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
