// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelCurrentUser model current user
//
// swagger:model model.CurrentUser
type ModelCurrentUser struct {

	// avatar url
	AvatarURL string `json:"avatar_url,omitempty"`

	// avg points
	AvgPoints int64 `json:"avg_points,omitempty"`

	// avg rank
	AvgRank int64 `json:"avg_rank,omitempty"`

	// avg rank percent
	AvgRankPercent int64 `json:"avg_rank_percent,omitempty"`

	// balance
	Balance float64 `json:"balance,omitempty"`

	// banned
	Banned bool `json:"banned,omitempty"`

	// follower count
	FollowerCount int64 `json:"follower_count,omitempty"`

	// following count
	FollowingCount int64 `json:"following_count,omitempty"`

	// games played
	GamesPlayed int64 `json:"games_played,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// influencer
	Influencer bool `json:"influencer,omitempty"`

	// moderator
	Moderator bool `json:"moderator,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// paypal email
	PaypalEmail string `json:"paypal_email,omitempty"`

	// powerup boosts
	PowerupBoosts int64 `json:"powerup_boosts,omitempty"`

	// premium
	Premium bool `json:"premium,omitempty"`

	// ref code
	RefCode string `json:"ref_code,omitempty"`

	// ref code used
	RefCodeUsed bool `json:"ref_code_used,omitempty"`

	// subscription tier
	SubscriptionTier struct {
		ModelSubscriptionTier
	} `json:"subscription_tier,omitempty"`

	// verified
	Verified bool `json:"verified,omitempty"`
}

// Validate validates this model current user
func (m *ModelCurrentUser) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubscriptionTier(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelCurrentUser) validateSubscriptionTier(formats strfmt.Registry) error {
	if swag.IsZero(m.SubscriptionTier) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this model current user based on the context it is used
func (m *ModelCurrentUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSubscriptionTier(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelCurrentUser) contextValidateSubscriptionTier(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *ModelCurrentUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelCurrentUser) UnmarshalBinary(b []byte) error {
	var res ModelCurrentUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
