// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelLeaderboardPosition model leaderboard position
//
// swagger:model model.LeaderboardPosition
type ModelLeaderboardPosition struct {

	// position
	Position int64 `json:"position,omitempty"`
}

// Validate validates this model leaderboard position
func (m *ModelLeaderboardPosition) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model leaderboard position based on context it is used
func (m *ModelLeaderboardPosition) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelLeaderboardPosition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelLeaderboardPosition) UnmarshalBinary(b []byte) error {
	var res ModelLeaderboardPosition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
