// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelLatestMatchStat model latest match stat
//
// swagger:model model.LatestMatchStat
type ModelLatestMatchStat struct {

	// min played
	MinPlayed int64 `json:"min_played,omitempty"`

	// points
	Points int64 `json:"points,omitempty"`

	// team crest url
	TeamCrestURL string `json:"team_crest_url,omitempty"`

	// team name
	TeamName string `json:"team_name,omitempty"`
}

// Validate validates this model latest match stat
func (m *ModelLatestMatchStat) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model latest match stat based on context it is used
func (m *ModelLatestMatchStat) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelLatestMatchStat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelLatestMatchStat) UnmarshalBinary(b []byte) error {
	var res ModelLatestMatchStat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
