// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelGameEvent model game event
//
// swagger:model model.GameEvent
type ModelGameEvent struct {

	// id
	ID string `json:"id,omitempty"`

	// minute
	Minute int64 `json:"minute,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// player id
	PlayerID string `json:"player_id,omitempty"`

	// player name
	PlayerName string `json:"player_name,omitempty"`

	// powered up
	PoweredUp bool `json:"powered_up,omitempty"`

	// score
	Score float64 `json:"score,omitempty"`

	// team id
	TeamID string `json:"team_id,omitempty"`
}

// Validate validates this model game event
func (m *ModelGameEvent) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model game event based on context it is used
func (m *ModelGameEvent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelGameEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelGameEvent) UnmarshalBinary(b []byte) error {
	var res ModelGameEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
