// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelHistoricalGame model historical game
//
// swagger:model model.HistoricalGame
type ModelHistoricalGame struct {

	// date
	// Format: date-time
	Date string `json:"date,omitempty"`

	// match name
	MatchName string `json:"match_name,omitempty"`

	// num
	Num int64 `json:"num,omitempty"`

	// player count
	PlayerCount int64 `json:"player_count,omitempty"`

	// points
	Points float64 `json:"points,omitempty"`

	// prize
	Prize float64 `json:"prize,omitempty"`

	// rank
	Rank int64 `json:"rank,omitempty"`
}

// Validate validates this model historical game
func (m *ModelHistoricalGame) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model historical game based on context it is used
func (m *ModelHistoricalGame) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelHistoricalGame) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelHistoricalGame) UnmarshalBinary(b []byte) error {
	var res ModelHistoricalGame
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
