// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelGamePowerUp model game power up
//
// swagger:model model.GamePowerUp
type ModelGamePowerUp struct {

	// created at
	// Format: date-time
	CreatedAt string `json:"created_at,omitempty"`

	// duration
	Duration int64 `json:"duration,omitempty"`

	// null end means that powerup still active
	// Format: date-time
	EndedAt string `json:"ended_at,omitempty"`

	// game id
	GameID string `json:"game_id,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// minute
	Minute int64 `json:"minute,omitempty"`

	// Multiplier
	Multiplier float64 `json:"multiplier,omitempty"`

	// position
	Position int64 `json:"position,omitempty"`

	// powerup id
	PowerupID int64 `json:"powerup_id,omitempty"`

	// powerup name
	PowerupName string `json:"powerup_name,omitempty"`

	// second
	Second int64 `json:"second,omitempty"`
}

// Validate validates this model game power up
func (m *ModelGamePowerUp) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model game power up based on context it is used
func (m *ModelGamePowerUp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelGamePowerUp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelGamePowerUp) UnmarshalBinary(b []byte) error {
	var res ModelGamePowerUp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
