// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelUseReferralRequest model use referral request
//
// swagger:model model.UseReferralRequest
type ModelUseReferralRequest struct {

	// ref code
	// Required: true
	RefCode string `json:"ref_code,omitempty"`
}

// Validate validates this model use referral request
func (m *ModelUseReferralRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model use referral request based on context it is used
func (m *ModelUseReferralRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelUseReferralRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelUseReferralRequest) UnmarshalBinary(b []byte) error {
	var res ModelUseReferralRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
