// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelGameSwapRequest model game swap request
//
// swagger:model model.GameSwapRequest
type ModelGameSwapRequest struct {

	// new player id
	// Required: true
	NewPlayerID string `json:"new_player_id,omitempty"`

	// player pick id
	// Required: true
	PlayerPickID string `json:"player_pick_id,omitempty"`
}

// Validate validates this model game swap request
func (m *ModelGameSwapRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model game swap request based on context it is used
func (m *ModelGameSwapRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelGameSwapRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelGameSwapRequest) UnmarshalBinary(b []byte) error {
	var res ModelGameSwapRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
