// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelApplyDoubleUpRequest model apply double up request
//
// swagger:model model.ApplyDoubleUpRequest
type ModelApplyDoubleUpRequest struct {

	// option
	Option struct {
		ModelPowerupOption
	} `json:"option,omitempty"`

	// position
	// Required: true
	Position int64 `json:"position,omitempty"`
}

// Validate validates this model apply double up request
func (m *ModelApplyDoubleUpRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOption(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelApplyDoubleUpRequest) validateOption(formats strfmt.Registry) error {
	if swag.IsZero(m.Option) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this model apply double up request based on the context it is used
func (m *ModelApplyDoubleUpRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOption(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelApplyDoubleUpRequest) contextValidateOption(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *ModelApplyDoubleUpRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelApplyDoubleUpRequest) UnmarshalBinary(b []byte) error {
	var res ModelApplyDoubleUpRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
