// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelGameAllowedActions model game allowed actions
//
// swagger:model model.GameAllowedActions
type ModelGameAllowedActions struct {

	// bonus powerup left
	BonusPowerupLeft int64 `json:"bonus_powerup_left,omitempty"`

	// powerup left
	PowerupLeft []int64 `json:"powerup_left"`

	// swaps left
	SwapsLeft []int64 `json:"swaps_left"`
}

// Validate validates this model game allowed actions
func (m *ModelGameAllowedActions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model game allowed actions based on context it is used
func (m *ModelGameAllowedActions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelGameAllowedActions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelGameAllowedActions) UnmarshalBinary(b []byte) error {
	var res ModelGameAllowedActions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
