// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelActionSummary model action summary
//
// swagger:model model.ActionSummary
type ModelActionSummary struct {

	// count
	Count int64 `json:"count,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// points
	Points float64 `json:"points,omitempty"`
}

// Validate validates this model action summary
func (m *ModelActionSummary) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model action summary based on context it is used
func (m *ModelActionSummary) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelActionSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelActionSummary) UnmarshalBinary(b []byte) error {
	var res ModelActionSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
