// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelGameJoinRequest model game join request
//
// swagger:model model.GameJoinRequest
type ModelGameJoinRequest struct {

	// match id
	// Required: true
	MatchID string `json:"match_id,omitempty"`

	// picks
	// Required: true
	Picks []string `json:"picks"`
}

// Validate validates this model game join request
func (m *ModelGameJoinRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model game join request based on context it is used
func (m *ModelGameJoinRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelGameJoinRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelGameJoinRequest) UnmarshalBinary(b []byte) error {
	var res ModelGameJoinRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
