// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelGamePick model game pick
//
// swagger:model model.GamePick
type ModelGamePick struct {

	// When was this player no longer owned. Null means the player is still owned
	// Format: date-time
	End string `json:"end,omitempty"`

	// game id
	GameID string `json:"game_id,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// is playing
	IsPlaying bool `json:"is_playing,omitempty"`

	// The last modification of any event that is represented in the score
	// Format: date-time
	LastModifiedEvent string `json:"last_modified_event,omitempty"`

	// minute
	Minute int64 `json:"minute,omitempty"`

	// player id
	PlayerID string `json:"player_id,omitempty"`

	// card position starting with card 1 {1, 2, 3, 4}
	Position int64 `json:"position,omitempty"`

	// Total points of the footballer pick, including powerup bonuses
	Score float64 `json:"score,omitempty"`

	// second
	Second int64 `json:"second,omitempty"`

	// start
	// Format: date-time
	Start string `json:"start,omitempty"`

	// user swapped
	UserSwapped bool `json:"user_swapped,omitempty"`
}

// Validate validates this model game pick
func (m *ModelGamePick) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model game pick based on context it is used
func (m *ModelGamePick) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelGamePick) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelGamePick) UnmarshalBinary(b []byte) error {
	var res ModelGamePick
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
