// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewLeaderboardEntry new leaderboard entry
//
// swagger:model NewLeaderboardEntry
type NewLeaderboardEntry struct {

	// current user
	CurrentUser bool `json:"current_user"`

	// rank
	Rank int64 `json:"rank"`

	// total score
	TotalScore float64 `json:"total_score"`

	// user id
	UserID string `json:"user_id,omitempty"`

	// user name
	UserName string `json:"user_name"`

	// week average rank
	WeekAverageRank *float64 `json:"week_average_rank,omitempty"`

	// week matches played
	WeekMatchesPlayed *int64 `json:"week_matches_played,omitempty"`
}

// Validate validates this new leaderboard entry
func (m *NewLeaderboardEntry) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this new leaderboard entry based on context it is used
func (m *NewLeaderboardEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewLeaderboardEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewLeaderboardEntry) UnmarshalBinary(b []byte) error {
	var res NewLeaderboardEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
