// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NullInt null int
//
// swagger:model null.Int
type NullInt struct {

	// int
	Int int64 `json:"int,omitempty"`

	// valid
	Valid bool `json:"valid,omitempty"`
}

// Validate validates this null int
func (m *NullInt) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this null int based on context it is used
func (m *NullInt) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NullInt) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NullInt) UnmarshalBinary(b []byte) error {
	var res NullInt
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
