// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NullString null string
//
// swagger:model null.String
type NullString struct {

	// string
	String string `json:"string,omitempty"`

	// valid
	Valid bool `json:"valid,omitempty"`
}

// Validate validates this null string
func (m *NullString) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this null string based on context it is used
func (m *NullString) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NullString) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NullString) UnmarshalBinary(b []byte) error {
	var res NullString
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
