// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// PaymentPlatformStatus payment platform status
//
// swagger:model PaymentPlatformStatus
type PaymentPlatformStatus int64

// for schema
var paymentPlatformStatusEnum []interface{}

func init() {
	var res []PaymentPlatformStatus
	if err := json.Unmarshal([]byte(`[0,1,2,3]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		paymentPlatformStatusEnum = append(paymentPlatformStatusEnum, v)
	}
}

func (m PaymentPlatformStatus) validatePaymentPlatformStatusEnum(path, location string, value PaymentPlatformStatus) error {
	if err := validate.EnumCase(path, location, value, paymentPlatformStatusEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this payment platform status
func (m PaymentPlatformStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validatePaymentPlatformStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this payment platform status based on context it is used
func (m PaymentPlatformStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
