// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// PaymentType payment type
//
// swagger:model PaymentType
type PaymentType int64

// for schema
var paymentTypeEnum []interface{}

func init() {
	var res []PaymentType
	if err := json.Unmarshal([]byte(`[1,2]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		paymentTypeEnum = append(paymentTypeEnum, v)
	}
}

func (m PaymentType) validatePaymentTypeEnum(path, location string, value PaymentType) error {
	if err := validate.EnumCase(path, location, value, paymentTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this payment type
func (m PaymentType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validatePaymentTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this payment type based on context it is used
func (m PaymentType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
