// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostChatMessageRequest post chat message request
//
// swagger:model PostChatMessageRequest
type PostChatMessageRequest struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this post chat message request
func (m *PostChatMessageRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post chat message request based on context it is used
func (m *PostChatMessageRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostChatMessageRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostChatMessageRequest) UnmarshalBinary(b []byte) error {
	var res PostChatMessageRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
