// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/itemslabs/clubz-api/types"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PowerUp power up
//
// swagger:model PowerUp
type PowerUp struct {

	// shows which actions power-up is affecting
	Actions []*Action `json:"actions"`

	// cost
	Cost *types.FloatWithZero `json:"cost,omitempty"`

	// description
	Description string `json:"description"`

	// duration in seconds
	Duration int64 `json:"duration"`

	// icon url
	IconURL *string `json:"icon_url"`

	// id
	ID int64 `json:"id"`

	// multiplier
	Multiplier *types.FloatWithZero `json:"multiplier,omitempty"`

	// name
	Name string `json:"name"`
}

// Validate validates this power up
func (m *PowerUp) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCost(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMultiplier(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PowerUp) validateActions(formats strfmt.Registry) error {
	if swag.IsZero(m.Actions) { // not required
		return nil
	}

	for i := 0; i < len(m.Actions); i++ {
		if swag.IsZero(m.Actions[i]) { // not required
			continue
		}

		if m.Actions[i] != nil {
			if err := m.Actions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("actions" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("actions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *PowerUp) validateCost(formats strfmt.Registry) error {
	if swag.IsZero(m.Cost) { // not required
		return nil
	}

	if m.Cost != nil {
		if err := m.Cost.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cost")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("cost")
			}
			return err
		}
	}

	return nil
}

func (m *PowerUp) validateMultiplier(formats strfmt.Registry) error {
	if swag.IsZero(m.Multiplier) { // not required
		return nil
	}

	if m.Multiplier != nil {
		if err := m.Multiplier.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("multiplier")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("multiplier")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this power up based on the context it is used
func (m *PowerUp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateActions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCost(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMultiplier(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PowerUp) contextValidateActions(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Actions); i++ {

		if m.Actions[i] != nil {

			if swag.IsZero(m.Actions[i]) { // not required
				return nil
			}

			if err := m.Actions[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("actions" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("actions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *PowerUp) contextValidateCost(ctx context.Context, formats strfmt.Registry) error {

	if m.Cost != nil {

		if swag.IsZero(m.Cost) { // not required
			return nil
		}

		if err := m.Cost.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cost")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("cost")
			}
			return err
		}
	}

	return nil
}

func (m *PowerUp) contextValidateMultiplier(ctx context.Context, formats strfmt.Registry) error {

	if m.Multiplier != nil {

		if swag.IsZero(m.Multiplier) { // not required
			return nil
		}

		if err := m.Multiplier.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("multiplier")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("multiplier")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PowerUp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PowerUp) UnmarshalBinary(b []byte) error {
	var res PowerUp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
