// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProgressionBar progression bar
//
// swagger:model ProgressionBar
type ProgressionBar struct {

	// current
	Current float64 `json:"current"`

	// promotion
	Promotion float64 `json:"promotion"`

	// relegation
	Relegation float64 `json:"relegation"`
}

// Validate validates this progression bar
func (m *ProgressionBar) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this progression bar based on context it is used
func (m *ProgressionBar) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProgressionBar) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProgressionBar) UnmarshalBinary(b []byte) error {
	var res ProgressionBar
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
