// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RevenueCatPurchaseRequestEvent revenue cat purchase request event
//
// swagger:model RevenueCatPurchaseRequestEvent
type RevenueCatPurchaseRequestEvent struct {

	// app user id
	AppUserID string `json:"app_user_id,omitempty"`

	// original transaction id
	OriginalTransactionID string `json:"original_transaction_id,omitempty"`

	// product id
	ProductID string `json:"product_id,omitempty"`

	// purchased at ms
	PurchasedAtMs int64 `json:"purchased_at_ms,omitempty"`

	// store
	// Enum: [AMAZON APP_STORE MAC_APP_STORE PLAY_STORE PROMOTIONAL STRIPE]
	Store string `json:"store,omitempty"`

	// type
	// Enum: [TEST INITIAL_PURCHASE RENEWAL CANCELLATION UNCANCELLATION NON_RENEWING_PURCHASE SUBSCRIPTION_PAUSED EXPIRATION BILLING_ISSUE PRODUCT_CHANGE TRANSFER SUBSCRIPTION_EXTENDED TEMPORARY_ENTITLEMENT_GRANT]
	Type string `json:"type,omitempty"`
}

// Validate validates this revenue cat purchase request event
func (m *RevenueCatPurchaseRequestEvent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStore(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var revenueCatPurchaseRequestEventTypeStorePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["AMAZON","APP_STORE","MAC_APP_STORE","PLAY_STORE","PROMOTIONAL","STRIPE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		revenueCatPurchaseRequestEventTypeStorePropEnum = append(revenueCatPurchaseRequestEventTypeStorePropEnum, v)
	}
}

const (

	// RevenueCatPurchaseRequestEventStoreAMAZON captures enum value "AMAZON"
	RevenueCatPurchaseRequestEventStoreAMAZON string = "AMAZON"

	// RevenueCatPurchaseRequestEventStoreAPPSTORE captures enum value "APP_STORE"
	RevenueCatPurchaseRequestEventStoreAPPSTORE string = "APP_STORE"

	// RevenueCatPurchaseRequestEventStoreMACAPPSTORE captures enum value "MAC_APP_STORE"
	RevenueCatPurchaseRequestEventStoreMACAPPSTORE string = "MAC_APP_STORE"

	// RevenueCatPurchaseRequestEventStorePLAYSTORE captures enum value "PLAY_STORE"
	RevenueCatPurchaseRequestEventStorePLAYSTORE string = "PLAY_STORE"

	// RevenueCatPurchaseRequestEventStorePROMOTIONAL captures enum value "PROMOTIONAL"
	RevenueCatPurchaseRequestEventStorePROMOTIONAL string = "PROMOTIONAL"

	// RevenueCatPurchaseRequestEventStoreSTRIPE captures enum value "STRIPE"
	RevenueCatPurchaseRequestEventStoreSTRIPE string = "STRIPE"
)

// prop value enum
func (m *RevenueCatPurchaseRequestEvent) validateStoreEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, revenueCatPurchaseRequestEventTypeStorePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *RevenueCatPurchaseRequestEvent) validateStore(formats strfmt.Registry) error {
	if swag.IsZero(m.Store) { // not required
		return nil
	}

	// value enum
	if err := m.validateStoreEnum("store", "body", m.Store); err != nil {
		return err
	}

	return nil
}

var revenueCatPurchaseRequestEventTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["TEST","INITIAL_PURCHASE","RENEWAL","CANCELLATION","UNCANCELLATION","NON_RENEWING_PURCHASE","SUBSCRIPTION_PAUSED","EXPIRATION","BILLING_ISSUE","PRODUCT_CHANGE","TRANSFER","SUBSCRIPTION_EXTENDED","TEMPORARY_ENTITLEMENT_GRANT"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		revenueCatPurchaseRequestEventTypeTypePropEnum = append(revenueCatPurchaseRequestEventTypeTypePropEnum, v)
	}
}

const (

	// RevenueCatPurchaseRequestEventTypeTEST captures enum value "TEST"
	RevenueCatPurchaseRequestEventTypeTEST string = "TEST"

	// RevenueCatPurchaseRequestEventTypeINITIALPURCHASE captures enum value "INITIAL_PURCHASE"
	RevenueCatPurchaseRequestEventTypeINITIALPURCHASE string = "INITIAL_PURCHASE"

	// RevenueCatPurchaseRequestEventTypeRENEWAL captures enum value "RENEWAL"
	RevenueCatPurchaseRequestEventTypeRENEWAL string = "RENEWAL"

	// RevenueCatPurchaseRequestEventTypeCANCELLATION captures enum value "CANCELLATION"
	RevenueCatPurchaseRequestEventTypeCANCELLATION string = "CANCELLATION"

	// RevenueCatPurchaseRequestEventTypeUNCANCELLATION captures enum value "UNCANCELLATION"
	RevenueCatPurchaseRequestEventTypeUNCANCELLATION string = "UNCANCELLATION"

	// RevenueCatPurchaseRequestEventTypeNONRENEWINGPURCHASE captures enum value "NON_RENEWING_PURCHASE"
	RevenueCatPurchaseRequestEventTypeNONRENEWINGPURCHASE string = "NON_RENEWING_PURCHASE"

	// RevenueCatPurchaseRequestEventTypeSUBSCRIPTIONPAUSED captures enum value "SUBSCRIPTION_PAUSED"
	RevenueCatPurchaseRequestEventTypeSUBSCRIPTIONPAUSED string = "SUBSCRIPTION_PAUSED"

	// RevenueCatPurchaseRequestEventTypeEXPIRATION captures enum value "EXPIRATION"
	RevenueCatPurchaseRequestEventTypeEXPIRATION string = "EXPIRATION"

	// RevenueCatPurchaseRequestEventTypeBILLINGISSUE captures enum value "BILLING_ISSUE"
	RevenueCatPurchaseRequestEventTypeBILLINGISSUE string = "BILLING_ISSUE"

	// RevenueCatPurchaseRequestEventTypePRODUCTCHANGE captures enum value "PRODUCT_CHANGE"
	RevenueCatPurchaseRequestEventTypePRODUCTCHANGE string = "PRODUCT_CHANGE"

	// RevenueCatPurchaseRequestEventTypeTRANSFER captures enum value "TRANSFER"
	RevenueCatPurchaseRequestEventTypeTRANSFER string = "TRANSFER"

	// RevenueCatPurchaseRequestEventTypeSUBSCRIPTIONEXTENDED captures enum value "SUBSCRIPTION_EXTENDED"
	RevenueCatPurchaseRequestEventTypeSUBSCRIPTIONEXTENDED string = "SUBSCRIPTION_EXTENDED"

	// RevenueCatPurchaseRequestEventTypeTEMPORARYENTITLEMENTGRANT captures enum value "TEMPORARY_ENTITLEMENT_GRANT"
	RevenueCatPurchaseRequestEventTypeTEMPORARYENTITLEMENTGRANT string = "TEMPORARY_ENTITLEMENT_GRANT"
)

// prop value enum
func (m *RevenueCatPurchaseRequestEvent) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, revenueCatPurchaseRequestEventTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *RevenueCatPurchaseRequestEvent) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this revenue cat purchase request event based on context it is used
func (m *RevenueCatPurchaseRequestEvent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RevenueCatPurchaseRequestEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RevenueCatPurchaseRequestEvent) UnmarshalBinary(b []byte) error {
	var res RevenueCatPurchaseRequestEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
