// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Rewards rewards
//
// swagger:model Rewards
type Rewards struct {

	// ball
	Ball int64 `json:"ball"`

	// credits
	Credits int64 `json:"credits"`

	// event tickets
	EventTickets int64 `json:"event_tickets"`

	// game token
	GameToken int64 `json:"game_token"`

	// id
	ID string `json:"id"`

	// kick off pack 1
	KickOffPack1 int64 `json:"kick_off_pack_1"`

	// kick off pack 2
	KickOffPack2 int64 `json:"kick_off_pack_2"`

	// kick off pack 3
	KickOffPack3 int64 `json:"kick_off_pack_3"`

	// lapt token
	LaptToken int64 `json:"lapt_token"`

	// name
	Name string `json:"name"`

	// season pack 1
	SeasonPack1 int64 `json:"season_pack_1"`

	// season pack 2
	SeasonPack2 int64 `json:"season_pack_2"`

	// season pack 3
	SeasonPack3 int64 `json:"season_pack_3"`

	// shirt
	Shirt int64 `json:"shirt"`

	// signed ball
	SignedBall int64 `json:"signed_ball"`

	// signed shirt
	SignedShirt int64 `json:"signed_shirt"`
}

// Validate validates this rewards
func (m *Rewards) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this rewards based on context it is used
func (m *Rewards) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Rewards) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Rewards) UnmarshalBinary(b []byte) error {
	var res Rewards
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
