// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ShortUser short user
//
// swagger:model ShortUser
type ShortUser struct {

	// avatar url
	AvatarURL string `json:"avatar_url"`

	// email
	Email string `json:"email"`

	// id
	ID string `json:"id"`

	// influencer
	Influencer bool `json:"influencer"`

	// moderator
	Moderator bool `json:"moderator"`

	// name
	Name string `json:"name"`

	// premium
	Premium bool `json:"premium"`

	// subscription tier
	SubscriptionTier SubscriptionTier `json:"subscription_tier,omitempty"`

	// verified
	Verified bool `json:"verified"`
}

// Validate validates this short user
func (m *ShortUser) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubscriptionTier(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ShortUser) validateSubscriptionTier(formats strfmt.Registry) error {
	if swag.IsZero(m.SubscriptionTier) { // not required
		return nil
	}

	if err := m.SubscriptionTier.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("subscription_tier")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("subscription_tier")
		}
		return err
	}

	return nil
}

// ContextValidate validate this short user based on the context it is used
func (m *ShortUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSubscriptionTier(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ShortUser) contextValidateSubscriptionTier(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.SubscriptionTier) { // not required
		return nil
	}

	if err := m.SubscriptionTier.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("subscription_tier")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("subscription_tier")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ShortUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ShortUser) UnmarshalBinary(b []byte) error {
	var res ShortUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
