// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdatePayPalEmailRequest update pay pal email request
//
// swagger:model UpdatePayPalEmailRequest
type UpdatePayPalEmailRequest struct {

	// paypal email
	// Required: true
	PaypalEmail *string `json:"paypal_email"`
}

// Validate validates this update pay pal email request
func (m *UpdatePayPalEmailRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePaypalEmail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdatePayPalEmailRequest) validatePaypalEmail(formats strfmt.Registry) error {

	if err := validate.Required("paypal_email", "body", m.PaypalEmail); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this update pay pal email request based on context it is used
func (m *UpdatePayPalEmailRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdatePayPalEmailRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdatePayPalEmailRequest) UnmarshalBinary(b []byte) error {
	var res UpdatePayPalEmailRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
