// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateBadgeRequest update badge request
//
// swagger:model UpdateBadgeRequest
type UpdateBadgeRequest struct {

	// description
	// Example: Updated description for the badge.
	Description string `json:"description,omitempty"`

	// image
	// Example: https://example.com/image-updated.png
	Image string `json:"image,omitempty"`

	// name
	// Example: Updated Champion Badge
	Name string `json:"name,omitempty"`

	// points
	// Example: 150
	Points int64 `json:"points,omitempty"`

	// status
	// Example: inactive
	Status string `json:"status,omitempty"`

	// type
	// Example: platinum
	Type string `json:"type,omitempty"`
}

// Validate validates this update badge request
func (m *UpdateBadgeRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update badge request based on context it is used
func (m *UpdateBadgeRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateBadgeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateBadgeRequest) UnmarshalBinary(b []byte) error {
	var res UpdateBadgeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
