// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateActionRequest update action request
//
// swagger:model UpdateActionRequest
type UpdateActionRequest struct {

	// description
	Description string `json:"description,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// score
	Score float64 `json:"score,omitempty"`
}

// Validate validates this update action request
func (m *UpdateActionRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update action request based on context it is used
func (m *UpdateActionRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateActionRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateActionRequest) UnmarshalBinary(b []byte) error {
	var res UpdateActionRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
