// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UseReferralRequest use referral request
//
// swagger:model UseReferralRequest
type UseReferralRequest struct {

	// ref code
	// Required: true
	RefCode *string `json:"ref_code"`
}

// Validate validates this use referral request
func (m *UseReferralRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRefCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UseReferralRequest) validateRefCode(formats strfmt.Registry) error {

	if err := validate.Required("ref_code", "body", m.RefCode); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this use referral request based on context it is used
func (m *UseReferralRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UseReferralRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UseReferralRequest) UnmarshalBinary(b []byte) error {
	var res UseReferralRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
