// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// User user
//
// swagger:model User
type User struct {

	// avatar url
	AvatarURL string `json:"avatar_url"`

	// avg points
	AvgPoints *int64 `json:"avg_points"`

	// avg rank
	AvgRank *int64 `json:"avg_rank"`

	// avg rank percent
	AvgRankPercent *int64 `json:"avg_rank_percent"`

	// email
	Email string `json:"email"`

	// follower count
	FollowerCount int64 `json:"follower_count"`

	// following count
	FollowingCount int64 `json:"following_count"`

	// games played
	GamesPlayed int64 `json:"games_played"`

	// id
	ID string `json:"id"`

	// influencer
	Influencer bool `json:"influencer"`

	// is following
	IsFollowing bool `json:"is_following"`

	// name
	Name string `json:"name"`

	// premium
	Premium bool `json:"premium"`

	// subscription tier
	SubscriptionTier SubscriptionTier `json:"subscription_tier,omitempty"`

	// verified
	Verified bool `json:"verified"`

	// wallet address
	WalletAddress string `json:"wallet_address"`
}

// Validate validates this user
func (m *User) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubscriptionTier(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *User) validateSubscriptionTier(formats strfmt.Registry) error {
	if swag.IsZero(m.SubscriptionTier) { // not required
		return nil
	}

	if err := m.SubscriptionTier.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("subscription_tier")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("subscription_tier")
		}
		return err
	}

	return nil
}

// ContextValidate validate this user based on the context it is used
func (m *User) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSubscriptionTier(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *User) contextValidateSubscriptionTier(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.SubscriptionTier) { // not required
		return nil
	}

	if err := m.SubscriptionTier.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("subscription_tier")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("subscription_tier")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *User) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *User) UnmarshalBinary(b []byte) error {
	var res User
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
