name: "[dev] K8S Api Deploy"
defaults:
  run:
    shell: bash

env:
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  ENV: dev
  NAMESPACE: fanclash-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  laliga-matchfantasy-api:
    name: laliga-matchfantasy-api
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600

      - name: Configure Kubectl for DOKS
        run: doctl kubernetes cluster kubeconfig save dev-fanclash

      - name: Build and Push Docker Image
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          DOCKER_IMAGE="laliga-matchfantasy-api:$SHORT_SHA"
          docker build -t $DOCKER_IMAGE .
          docker tag $DOCKER_IMAGE registry.digitalocean.com/gameon-ams3/$DOCKER_IMAGE
          docker push registry.digitalocean.com/gameon-ams3/$DOCKER_IMAGE

      - name: Update Image Tag in K8S Deployment
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          sed -i 's/TAG_PLACEHOLDER/'"$SHORT_SHA"'/g' $GITHUB_WORKSPACE/images/laliga-matchfantasy-api/deployment_${{ env.ENV }}.yaml

      - name: K8S Api Deploy
        run: |
            kubectl apply -f images/laliga-matchfantasy-api/deployment_${{ env.ENV }}.yaml
            kubectl apply -f images/laliga-matchfantasy-api/service_${{ env.ENV }}.yml
      
      - name: Check Deployment Health and Rollback if Necessary
        run: |
          if ! kubectl rollout status deployment/fanclash-api -n $NAMESPACE; then
            echo "Deployment health check failed. Rolling back..."
            kubectl rollout undo deployment/fanclash-api -n $NAMESPACE
          else
            echo "Deployment is healthy."
          fi
        timeout-minutes: 5

      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: staging-deployments
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_STAGING_URL }}
          SLACK_ICON_EMOJI: ':gameon:'
          SLACK_USERNAME: GitHubAction
          SLACK_COLOR: ${{ job.status }} # Sets the color of the Slack notification bar to red for failures
          SLACK_TITLE: 'Dev Laliga API K8s deployment. Commit message: ${{ github.event.head_commit.message }}'
          SLACK_FOOTER: Powered By GameOn DevOps team