name: "[prod] Clubz API Deploy"
defaults:
  run:
    shell: bash

env:
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  ENV: prod
  NAMESPACE: clubz-prod

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  clubz-api:
    name: clubz-api
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600

      - name: Configure Kubectl for DOKS
        run: doctl kubernetes cluster kubeconfig save clubz-platform-cluster

      - name: Build and Push Docker Image
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          DOCKER_IMAGE="clubz-api:$SHORT_SHA"
          docker build -t $DOCKER_IMAGE .
          # Tagging
          docker tag $DOCKER_IMAGE registry.digitalocean.com/clubz-platform-registry/$DOCKER_IMAGE
          docker tag $DOCKER_IMAGE registry.digitalocean.com/clubz-platform-registry/clubz-api:prod
          # Pushing
          docker push registry.digitalocean.com/clubz-platform-registry/$DOCKER_IMAGE
          docker push registry.digitalocean.com/clubz-platform-registry/clubz-api:prod

      - name: Update Kubernetes Deployment
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          kubectl set image deployment/clubz-api clubz-api=registry.digitalocean.com/clubz-platform-registry/clubz-api:$SHORT_SHA -n $NAMESPACE

      - name: Check Deployment Health and Rollback if Necessary
        run: |
          if ! kubectl rollout status deployment/clubz-api -n $NAMESPACE --timeout=300s; then
            echo "Deployment health check failed. Rolling back..."
            kubectl rollout undo deployment/clubz-api -n $NAMESPACE
          else
            echo "Deployment is healthy."
          fi
        timeout-minutes: 5

      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: production-deployments
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PRD_URL }}
          SLACK_ICON_EMOJI: ':rocket:'
          SLACK_USERNAME: GitHubAction
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: 'Prod Clubz API K8s deployment. Commit message: ${{ github.event.head_commit.message }}'
          SLACK_FOOTER: Powered By Clubz DevOps team